// +build go1.9

// Copyright 2019 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/Azure/azure-sdk-for-go/tools/profileBuilder

package sql

import (
	"context"

	original "github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2018-06-01-preview/sql"
)

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type IdentityType = original.IdentityType

const (
	SystemAssigned IdentityType = original.SystemAssigned
)

type InstancePoolLicenseType = original.InstancePoolLicenseType

const (
	BasePrice       InstancePoolLicenseType = original.BasePrice
	LicenseIncluded InstancePoolLicenseType = original.LicenseIncluded
)

type ManagedInstanceLicenseType = original.ManagedInstanceLicenseType

const (
	ManagedInstanceLicenseTypeBasePrice       ManagedInstanceLicenseType = original.ManagedInstanceLicenseTypeBasePrice
	ManagedInstanceLicenseTypeLicenseIncluded ManagedInstanceLicenseType = original.ManagedInstanceLicenseTypeLicenseIncluded
)

type ManagedInstanceProxyOverride = original.ManagedInstanceProxyOverride

const (
	Default  ManagedInstanceProxyOverride = original.Default
	Proxy    ManagedInstanceProxyOverride = original.Proxy
	Redirect ManagedInstanceProxyOverride = original.Redirect
)

type ManagedServerCreateMode = original.ManagedServerCreateMode

const (
	ManagedServerCreateModeDefault            ManagedServerCreateMode = original.ManagedServerCreateModeDefault
	ManagedServerCreateModePointInTimeRestore ManagedServerCreateMode = original.ManagedServerCreateModePointInTimeRestore
)

type SecurityAlertPolicyState = original.SecurityAlertPolicyState

const (
	SecurityAlertPolicyStateDisabled SecurityAlertPolicyState = original.SecurityAlertPolicyStateDisabled
	SecurityAlertPolicyStateEnabled  SecurityAlertPolicyState = original.SecurityAlertPolicyStateEnabled
	SecurityAlertPolicyStateNew      SecurityAlertPolicyState = original.SecurityAlertPolicyStateNew
)

type SensitivityLabelSource = original.SensitivityLabelSource

const (
	DatabaseStatusAutoClosed                        DatabaseStatus = original.DatabaseStatusAutoClosed
	DatabaseStatusCopying                           DatabaseStatus = original.DatabaseStatusCopying
	DatabaseStatusCreating                          DatabaseStatus = original.DatabaseStatusCreating
	DatabaseStatusDisabled                          DatabaseStatus = original.DatabaseStatusDisabled
	DatabaseStatusEmergencyMode                     DatabaseStatus = original.DatabaseStatusEmergencyMode
	DatabaseStatusInaccessible                      DatabaseStatus = original.DatabaseStatusInaccessible
	DatabaseStatusOffline                           DatabaseStatus = original.DatabaseStatusOffline
	DatabaseStatusOfflineChangingDwPerformanceTiers DatabaseStatus = original.DatabaseStatusOfflineChangingDwPerformanceTiers
	DatabaseStatusOfflineSecondary                  DatabaseStatus = original.DatabaseStatusOfflineSecondary
	DatabaseStatusOnline                            DatabaseStatus = original.DatabaseStatusOnline
	DatabaseStatusOnlineChangingDwPerformanceTiers  DatabaseStatus = original.DatabaseStatusOnlineChangingDwPerformanceTiers
	DatabaseStatusPaused                            DatabaseStatus = original.DatabaseStatusPaused
	DatabaseStatusPausing                           DatabaseStatus = original.DatabaseStatusPausing
	DatabaseStatusRecovering                        DatabaseStatus = original.DatabaseStatusRecovering
	DatabaseStatusRecoveryPending                   DatabaseStatus = original.DatabaseStatusRecoveryPending
	DatabaseStatusRestoring                         DatabaseStatus = original.DatabaseStatusRestoring
	DatabaseStatusResuming                          DatabaseStatus = original.DatabaseStatusResuming
	DatabaseStatusScaling                           DatabaseStatus = original.DatabaseStatusScaling
	DatabaseStatusShutdown                          DatabaseStatus = original.DatabaseStatusShutdown
	DatabaseStatusStandby                           DatabaseStatus = original.DatabaseStatusStandby
	DatabaseStatusSuspect                           DatabaseStatus = original.DatabaseStatusSuspect
)

type BaseClient = original.BaseClient
type DatabaseSecurityAlertListResult = original.DatabaseSecurityAlertListResult
type DatabaseSecurityAlertListResultIterator = original.DatabaseSecurityAlertListResultIterator
type DatabaseSecurityAlertListResultPage = original.DatabaseSecurityAlertListResultPage
type DatabaseSecurityAlertPoliciesClient = original.DatabaseSecurityAlertPoliciesClient
type DatabaseSecurityAlertPolicy = original.DatabaseSecurityAlertPolicy
type DatabasesClient = original.DatabasesClient
type DatabasesFailoverFuture = original.DatabasesFailoverFuture
type ElasticPoolsClient = original.ElasticPoolsClient
type ElasticPoolsCreateOrUpdateFuture = original.ElasticPoolsCreateOrUpdateFuture
type ElasticPoolsDeleteFuture = original.ElasticPoolsDeleteFuture
type ElasticPoolsUpdateFuture = original.ElasticPoolsUpdateFuture
type InstanceFailoverGroup = original.InstanceFailoverGroup
type InstanceFailoverGroupListResult = original.InstanceFailoverGroupListResult
type InstanceFailoverGroupListResultIterator = original.InstanceFailoverGroupListResultIterator
type InstanceFailoverGroupListResultPage = original.InstanceFailoverGroupListResultPage
type InstanceFailoverGroupProperties = original.InstanceFailoverGroupProperties
type InstanceFailoverGroupReadOnlyEndpoint = original.InstanceFailoverGroupReadOnlyEndpoint
type InstanceFailoverGroupReadWriteEndpoint = original.InstanceFailoverGroupReadWriteEndpoint
type InstanceFailoverGroupsClient = original.InstanceFailoverGroupsClient
type InstanceFailoverGroupsCreateOrUpdateFuture = original.InstanceFailoverGroupsCreateOrUpdateFuture
type InstanceFailoverGroupsDeleteFuture = original.InstanceFailoverGroupsDeleteFuture
type InstanceFailoverGroupsFailoverFuture = original.InstanceFailoverGroupsFailoverFuture
type InstanceFailoverGroupsForceFailoverAllowDataLossFuture = original.InstanceFailoverGroupsForceFailoverAllowDataLossFuture
type LicenseTypeCapability = original.LicenseTypeCapability
type LocationCapabilities = original.LocationCapabilities
type LogSizeCapability = original.LogSizeCapability
type ManagedDatabaseVulnerabilityAssessmentRuleBaselinesClient = original.ManagedDatabaseVulnerabilityAssessmentRuleBaselinesClient
type ManagedDatabaseVulnerabilityAssessmentScansClient = original.ManagedDatabaseVulnerabilityAssessmentScansClient
type ManagedDatabaseVulnerabilityAssessmentScansInitiateScanFuture = original.ManagedDatabaseVulnerabilityAssessmentScansInitiateScanFuture
type ManagedDatabaseVulnerabilityAssessmentsClient = original.ManagedDatabaseVulnerabilityAssessmentsClient
type ManagedInstanceEditionCapability = original.ManagedInstanceEditionCapability
type ManagedInstanceEncryptionProtector = original.ManagedInstanceEncryptionProtector
type ManagedInstanceEncryptionProtectorListResult = original.ManagedInstanceEncryptionProtectorListResult
type ManagedInstanceEncryptionProtectorListResultIterator = original.ManagedInstanceEncryptionProtectorListResultIterator
type ManagedInstanceEncryptionProtectorListResultPage = original.ManagedInstanceEncryptionProtectorListResultPage
type ManagedInstanceEncryptionProtectorProperties = original.ManagedInstanceEncryptionProtectorProperties
type ManagedInstanceEncryptionProtectorsClient = original.ManagedInstanceEncryptionProtectorsClient
type ManagedInstanceEncryptionProtectorsCreateOrUpdateFuture = original.ManagedInstanceEncryptionProtectorsCreateOrUpdateFuture
type ManagedInstanceEncryptionProtectorsRevalidateFuture = original.ManagedInstanceEncryptionProtectorsRevalidateFuture
type ManagedInstanceFamilyCapability = original.ManagedInstanceFamilyCapability
type ManagedInstanceKey = original.ManagedInstanceKey
type ManagedInstanceKeyListResult = original.ManagedInstanceKeyListResult
type ManagedInstanceKeyListResultIterator = original.ManagedInstanceKeyListResultIterator
type ManagedInstanceKeyListResultPage = original.ManagedInstanceKeyListResultPage
type ManagedInstanceKeyProperties = original.ManagedInstanceKeyProperties
type ManagedInstanceKeysClient = original.ManagedInstanceKeysClient
type ManagedInstanceKeysCreateOrUpdateFuture = original.ManagedInstanceKeysCreateOrUpdateFuture
type ManagedInstanceKeysDeleteFuture = original.ManagedInstanceKeysDeleteFuture
type ManagedInstancePairInfo = original.ManagedInstancePairInfo
type ManagedInstanceTdeCertificatesClient = original.ManagedInstanceTdeCertificatesClient
type ManagedInstanceTdeCertificatesCreateFuture = original.ManagedInstanceTdeCertificatesCreateFuture
type ManagedInstanceVcoresCapability = original.ManagedInstanceVcoresCapability
type ManagedInstanceVersionCapability = original.ManagedInstanceVersionCapability
type MaxSizeCapability = original.MaxSizeCapability
type MaxSizeRangeCapability = original.MaxSizeRangeCapability
type PartnerRegionInfo = original.PartnerRegionInfo
type PerformanceLevelCapability = original.PerformanceLevelCapability
type ProxyResource = original.ProxyResource
type Resource = original.Resource
type ResourceIdentity = original.ResourceIdentity
type SecurityAlertPolicyProperties = original.SecurityAlertPolicyProperties
type SensitivityLabel = original.SensitivityLabel
type SensitivityLabelListResult = original.SensitivityLabelListResult
type SensitivityLabelListResultIterator = original.SensitivityLabelListResultIterator
type SensitivityLabelListResultPage = original.SensitivityLabelListResultPage
type SensitivityLabelProperties = original.SensitivityLabelProperties
type ServerVulnerabilityAssessment = original.ServerVulnerabilityAssessment
type ServerVulnerabilityAssessmentListResult = original.ServerVulnerabilityAssessmentListResult
type ServerVulnerabilityAssessmentListResultIterator = original.ServerVulnerabilityAssessmentListResultIterator
type ServerVulnerabilityAssessmentListResultPage = original.ServerVulnerabilityAssessmentListResultPage
type ServerVulnerabilityAssessmentProperties = original.ServerVulnerabilityAssessmentProperties
type ServerVulnerabilityAssessmentsClient = original.ServerVulnerabilityAssessmentsClient
type Sku = original.Sku
type TrackedResource = original.TrackedResource
type Usage = original.Usage
type UsageListResult = original.UsageListResult
type UsageListResultIterator = original.UsageListResultIterator
type UsageListResultPage = original.UsageListResultPage
type UsagesClient = original.UsagesClient
type VulnerabilityAssessmentRecurringScansProperties = original.VulnerabilityAssessmentRecurringScansProperties

func New(subscriptionID string) BaseClient {
	return original.New(subscriptionID)
}
func NewDatabaseSecurityAlertListResultIterator(page DatabaseSecurityAlertListResultPage) DatabaseSecurityAlertListResultIterator {
	return original.NewDatabaseSecurityAlertListResultIterator(page)
}
func NewDatabaseSecurityAlertListResultPage(getNextPage func(context.Context, DatabaseSecurityAlertListResult) (DatabaseSecurityAlertListResult, error)) DatabaseSecurityAlertListResultPage {
	return original.NewDatabaseSecurityAlertListResultPage(getNextPage)
}
func NewDatabaseSecurityAlertPoliciesClient(subscriptionID string) DatabaseSecurityAlertPoliciesClient {
	return original.NewDatabaseSecurityAlertPoliciesClient(subscriptionID)
}
func NewDatabaseSecurityAlertPoliciesClientWithBaseURI(baseURI string, subscriptionID string) DatabaseSecurityAlertPoliciesClient {
	return original.NewDatabaseSecurityAlertPoliciesClientWithBaseURI(baseURI, subscriptionID)
}
func NewDatabasesClient(subscriptionID string) DatabasesClient {
	return original.NewDatabasesClient(subscriptionID)
}
func NewDatabasesClientWithBaseURI(baseURI string, subscriptionID string) DatabasesClient {
	return original.NewDatabasesClientWithBaseURI(baseURI, subscriptionID)
}
func NewElasticPoolsClient(subscriptionID string) ElasticPoolsClient {
	return original.NewElasticPoolsClient(subscriptionID)
}
func NewElasticPoolsClientWithBaseURI(baseURI string, subscriptionID string) ElasticPoolsClient {
	return original.NewElasticPoolsClientWithBaseURI(baseURI, subscriptionID)
}
func NewInstancePoolListResultIterator(page InstancePoolListResultPage) InstancePoolListResultIterator {
	return original.NewInstancePoolListResultIterator(page)
}
func NewInstancePoolListResultPage(getNextPage func(context.Context, InstancePoolListResult) (InstancePoolListResult, error)) InstancePoolListResultPage {
	return original.NewInstancePoolListResultPage(getNextPage)
}
func NewInstancePoolsClient(subscriptionID string) InstancePoolsClient {
	return original.NewInstancePoolsClient(subscriptionID)
}
func NewInstancePoolsClientWithBaseURI(baseURI string, subscriptionID string) InstancePoolsClient {
	return original.NewInstancePoolsClientWithBaseURI(baseURI, subscriptionID)
}
func NewManagedDatabaseSensitivityLabelsClient(subscriptionID string) ManagedDatabaseSensitivityLabelsClient {
	return original.NewManagedDatabaseSensitivityLabelsClient(subscriptionID)
}
func NewManagedDatabaseSensitivityLabelsClientWithBaseURI(baseURI string, subscriptionID string) ManagedDatabaseSensitivityLabelsClient {
	return original.NewManagedDatabaseSensitivityLabelsClientWithBaseURI(baseURI, subscriptionID)
}
func NewManagedInstanceListResultIterator(page ManagedInstanceListResultPage) ManagedInstanceListResultIterator {
	return original.NewManagedInstanceListResultIterator(page)
}
func NewManagedInstanceListResultPage(getNextPage func(context.Context, ManagedInstanceListResult) (ManagedInstanceListResult, error)) ManagedInstanceListResultPage {
	return original.NewManagedInstanceListResultPage(getNextPage)
}
func NewManagedInstanceVulnerabilityAssessmentListResultIterator(page ManagedInstanceVulnerabilityAssessmentListResultPage) ManagedInstanceVulnerabilityAssessmentListResultIterator {
	return original.NewManagedInstanceVulnerabilityAssessmentListResultIterator(page)
}
func NewManagedInstanceVulnerabilityAssessmentListResultPage(getNextPage func(context.Context, ManagedInstanceVulnerabilityAssessmentListResult) (ManagedInstanceVulnerabilityAssessmentListResult, error)) ManagedInstanceVulnerabilityAssessmentListResultPage {
	return original.NewManagedInstanceVulnerabilityAssessmentListResultPage(getNextPage)
}
func NewManagedInstanceVulnerabilityAssessmentsClient(subscriptionID string) ManagedInstanceVulnerabilityAssessmentsClient {
	return original.NewManagedInstanceVulnerabilityAssessmentsClient(subscriptionID)
}
func NewManagedInstanceVulnerabilityAssessmentsClientWithBaseURI(baseURI string, subscriptionID string) ManagedInstanceVulnerabilityAssessmentsClient {
	return original.NewManagedInstanceVulnerabilityAssessmentsClientWithBaseURI(baseURI, subscriptionID)
}
func NewManagedInstancesClient(subscriptionID string) ManagedInstancesClient {
	return original.NewManagedInstancesClient(subscriptionID)
}
func NewManagedInstancesClientWithBaseURI(baseURI string, subscriptionID string) ManagedInstancesClient {
	return original.NewManagedInstancesClientWithBaseURI(baseURI, subscriptionID)
}
func NewPrivateEndpointConnectionListResultIterator(page PrivateEndpointConnectionListResultPage) PrivateEndpointConnectionListResultIterator {
	return original.NewPrivateEndpointConnectionListResultIterator(page)
}
func NewPrivateEndpointConnectionListResultPage(getNextPage func(context.Context, PrivateEndpointConnectionListResult) (PrivateEndpointConnectionListResult, error)) PrivateEndpointConnectionListResultPage {
	return original.NewPrivateEndpointConnectionListResultPage(getNextPage)
}
func NewPrivateEndpointConnectionsClient(subscriptionID string) PrivateEndpointConnectionsClient {
	return original.NewPrivateEndpointConnectionsClient(subscriptionID)
}
func NewPrivateEndpointConnectionsClientWithBaseURI(baseURI string, subscriptionID string) PrivateEndpointConnectionsClient {
	return original.NewPrivateEndpointConnectionsClientWithBaseURI(baseURI, subscriptionID)
}
func NewSensitivityLabelListResultIterator(page SensitivityLabelListResultPage) SensitivityLabelListResultIterator {
	return original.NewSensitivityLabelListResultIterator(page)
}
func NewSensitivityLabelListResultPage(getNextPage func(context.Context, SensitivityLabelListResult) (SensitivityLabelListResult, error)) SensitivityLabelListResultPage {
	return original.NewSensitivityLabelListResultPage(getNextPage)
}
func NewServerVulnerabilityAssessmentListResultIterator(page ServerVulnerabilityAssessmentListResultPage) ServerVulnerabilityAssessmentListResultIterator {
	return original.NewServerVulnerabilityAssessmentListResultIterator(page)
}
func NewServerVulnerabilityAssessmentListResultPage(getNextPage func(context.Context, ServerVulnerabilityAssessmentListResult) (ServerVulnerabilityAssessmentListResult, error)) ServerVulnerabilityAssessmentListResultPage {
	return original.NewServerVulnerabilityAssessmentListResultPage(getNextPage)
}
func NewServerVulnerabilityAssessmentsClient(subscriptionID string) ServerVulnerabilityAssessmentsClient {
	return original.NewServerVulnerabilityAssessmentsClient(subscriptionID)
}
func NewServerVulnerabilityAssessmentsClientWithBaseURI(baseURI string, subscriptionID string) ServerVulnerabilityAssessmentsClient {
	return original.NewServerVulnerabilityAssessmentsClientWithBaseURI(baseURI, subscriptionID)
}
func NewUsageListResultIterator(page UsageListResultPage) UsageListResultIterator {
	return original.NewUsageListResultIterator(page)
}
func NewUsageListResultPage(getNextPage func(context.Context, UsageListResult) (UsageListResult, error)) UsageListResultPage {
	return original.NewUsageListResultPage(getNextPage)
}
func NewUsagesClient(subscriptionID string) UsagesClient {
	return original.NewUsagesClient(subscriptionID)
}
func NewUsagesClientWithBaseURI(baseURI string, subscriptionID string) UsagesClient {
	return original.NewUsagesClientWithBaseURI(baseURI, subscriptionID)
}
func NewWithBaseURI(baseURI string, subscriptionID string) BaseClient {
	return original.NewWithBaseURI(baseURI, subscriptionID)
}
func PossibleIdentityTypeValues() []IdentityType {
	return original.PossibleIdentityTypeValues()
}
func PossibleInstancePoolLicenseTypeValues() []InstancePoolLicenseType {
	return original.PossibleInstancePoolLicenseTypeValues()
}
func PossibleManagedInstanceLicenseTypeValues() []ManagedInstanceLicenseType {
	return original.PossibleManagedInstanceLicenseTypeValues()
}
func PossibleManagedInstanceProxyOverrideValues() []ManagedInstanceProxyOverride {
	return original.PossibleManagedInstanceProxyOverrideValues()
}
func PossibleManagedServerCreateModeValues() []ManagedServerCreateMode {
	return original.PossibleManagedServerCreateModeValues()
}
func PossibleSecurityAlertPolicyStateValues() []SecurityAlertPolicyState {
	return original.PossibleSecurityAlertPolicyStateValues()
}
func PossibleSensitivityLabelSourceValues() []SensitivityLabelSource {
	return original.PossibleSensitivityLabelSourceValues()
}
func UserAgent() string {
	return original.UserAgent() + " profiles/preview"
}
func Version() string {
	return original.Version()
}
